### ISSUE TITLE
Twitter link not working

### ISSUE THREAD

**Issue by chelsea-banke** [Kanyelings/mentormatch-ng#48]
Twitter link for Chelsea Banke not working

**Comment by elroykanye** [comment]
I don't think so

**Comment by elroykanye** [comment]
Send me the link you opened

**Comment by elroykanye** [comment]
No.

**Comment by elroykanye** [comment]
Send the link of the mentor match site you are opening.

**Comment by chelsea-banke** [comment]
https://mentormatch-ng-plknlkqrf-kanyelings.vercel.app/

**Comment by elroykanye** [comment]
You were using the wrong link. I sent an updated link with the deployed build that already rectified that error.

**Comment by chelsea-banke** [comment]
Okay
